### The basics

- one dimention arrays and their attributes, shape, ndim, size
- two dimention arrays
- n dimention arrays

- how to access a given dimention and how to work with it

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5],  dtype = 'int32')
a

array([1, 2, 3, 4, 5], dtype=int32)

In [4]:
a.shape

(5,)

In [5]:
a.ndim

1

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
a.size

5

In [9]:
len(a)

5

In [10]:
a[:3]

array([1, 2, 3], dtype=int32)

#### Two dim arrays

In [11]:
a2 = np.array([[1, 2, 3, 4], 
               [2, 3, 1, 6]])
a2

array([[1, 2, 3, 4],
       [2, 3, 1, 6]])

In [12]:
a2

array([[1, 2, 3, 4],
       [2, 3, 1, 6]])

In [13]:
a2[0:1, 0:1]

array([[1]])

In [14]:
# replace the an element 
a2[0:1, 0:1] = 20

In [15]:
a2

array([[20,  2,  3,  4],
       [ 2,  3,  1,  6]])

In [16]:
# access the column 2 
a2[:, 2]

array([3, 1])

In [17]:
# access row one
a2[1, :]

array([2, 3, 1, 6])

In [18]:
a3 = np.array([[[1, 2,3 ], 
                [0, 2, 3], 
                [4, 5, 6]], 
               [[2, 5, 6],
                [3, 7, 8],
                [6, 8, 9]], 
               [[1, 0, 0], 
                [0, 0 ,1], 
                [3, 2, 1]]
             ])

In [19]:
a3.ndim

3

In [20]:
a3.shape

(3, 3, 3)

### Initializing different types of arrays

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((3, 3, 3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [24]:
np.full((3, 3, 3), 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [25]:
# random numbers
np.random.rand(4,2)

array([[0.01672963, 0.09386384],
       [0.81972306, 0.15891908],
       [0.96656845, 0.41806174],
       [0.32961952, 0.7539595 ]])

In [28]:
np.random.randint(7, size = (3,3))

array([[0, 5, 3],
       [3, 2, 2],
       [5, 6, 5]])

In [29]:
# identity matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Operations with arrays

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 3, 4, 1])
c = a + b
c

array([1, 5, 7, 5])

In [40]:
k = a -b
k

array([ 1, -1, -1,  3])

In [35]:
d = np.vstack((a,b))

In [36]:
d

array([[1, 2, 3, 4],
       [0, 3, 4, 1]])

In [37]:
f = np.hstack((a, b))
f

array([1, 2, 3, 4, 0, 3, 4, 1])

In [39]:
d.T

array([[1, 0],
       [2, 3],
       [3, 4],
       [4, 1]])